apiVersion: v1
kind: ConfigMap
metadata:
  name: staff-service-config
data:
  PORT: "3000"
  # Add other configuration variables here if needed
  # For example:
  # DB_HOST: "localhost"
  # DB_PORT: "5432"
